const learning = [
"Essentials",
"ReactJS",
"Python",
"JavaScript",
"Django",
"Flask",
"Node JS",
"Machine Learning",
"Docker",
"Blockchain",
"Web 101",
"TypeScript",
"Go",
"Firebase",
"Mongo DB",
"FAST API",
"Flutter",
"Serverless",
"React Native",
"Swift",
"Angular",
"Vue JS",
"Express JS",
"REST API",
]

const project = [
"SQL-Ease",
"Assignmentor",
"Graph Visualizer",
"Quotify",
"Emotional AI",
"Graphics Learning Tool",
"InMap",
"Image Gen",
"Chat Exporter",
"SheCare",
"Lattice TKMCE",
"TraWell",
"Titan Discord Bot",
"Simplify",
"Space Invaders",
"Gesture Volume Control",
"Drop Point",
"Dance Off",
"Tug of Words",
"Text Genie",
"Quiz Whiz",
"Quickfolio",
"Cherava",
"Stable Diffusion",
]

const venues = [
"Rajadhani Institute of Engineering and Technology, Attingal",
"Sree Buddha College of Engineering, Pattoor",
"College of Engineering, Vadakara",
"College of Engineering, Chengannur",
"Government Engineering College, Wayanad",
"Mar Baselios Christian College of Engineering and Technology, Peermade",
"TKM College of Engineering, Kollam",
"College of Engineering Thiruvananthapuram",
"Christ College of Engineering, Irinjalakkuda",
"TinkerSpace Kochi"
]

const mentors = [...new Set([
"ajmal.sajeev7@gmail.com",
"nihalyazinshamim23@gmail.com",
"abhijithsunil7000@gmail.com",
"adithyans121@gmail.com",
"akashfeb6@gmail.com",
"albertbenny193@gmail.com",
"albinisac131@gmail.com",
"arjunrmrm@gmail.com",
"asmakalam4@gmail.com",
"psaswathy202@gmail.com",
"alphamarkbravo@gmail.com",
"im.vishakcb@gmail.com",
"gokulpankaj2003@gmail.com",
"gopikasreedharan2002@gmail.com",
"irfansalim3@gmail.com",
"maneshmohan7994@gmail.com",
"mayankdj7001@gmail.com",
"najahnajm@gmail.com",
"mnikhil0006@gmail.com",
"nimminazir@gmail.com",
"noahrudy003@gmail.com",
"parthanskg@gmail.com",
"arjunkrishnar00@gmail.com",
"sarathleo106@gmail.com",
"sarinkrishnan718@gmail.com",
"sauravsunilthompil@gmail.com",
"unfetteredscholar1998@gmail.com",
"subinssatheesh02@gmail.com",
"vaishnavb0475@gmail.com",
"viswanathanpv19@gmail.com",
"abhianilkumar03@gmail.com",
"itzabhi95@gmail.com",
"adilhussain2k4@gmail.com",
"adithyasunil89@gmail.com",
"uadithyan191@gmail.com",
"afsanasameer097@gmail.com",
"ajmalahammed2003@gmail.com",
"akashmkumar007@gmail.com",
"akshayraj45623@gmail.com",
"alankalluvettankuzhy@gmail.com",
"amalsudheer616@gmail.com",
"anuanusreevlr@gmail.com",
"arishna3666@gmail.com",
"arunkrishna2004sini@gmail.com",
"ratspot919@gmail.com",
"deepikasanathanan1234@gmail.com",
"devaprasad8126@gmail.com",
"hafeesjafar77@gmail.com",
"haafizshamnad@gmail.com",
"karthikasathy45gmail.com",
"slaachu9956@gmail.com",
"naimisulphikar@gmail.com",
"nidhindev362@gmail.com",
"prapanchappuse789@gmail.com",
"rejin.raj.rajeev@gmail.com",
"snigdhaspostbox@gmail.com",
"encryptedaliyan127@gmail.com",
"raseefkv46@gmail.com",
"gopuanil2020@gmail.com",
"jawaharsreeram2003@gmail.com",
"apvkeezhana2000@gmail.com",
"aathsha@gmail.com",
"athishraj88@gmail.com",
"shravannanil02@gmail.com",
"muhammedck791@gmail.com",
"helnaj2006@gmail.com",
"sandrababuraj23@gmail.com",
"anuroopa.saji@gmail.com",
"shibinrasheed333@gmail.com",
"anjanats60@gmail.com",
"nandukrishnat3@gmail.com",
"vpsayooj84@gmail.com",
"anujithdasan123@gmail.com",
"anujadhyrianath293@gmail.com",
"zeenathkp401@gmail.com",
"aswinpsadan@gmail.com",
"ananthua241@gmail.com",
"ashashfaqh@gmail.com",
"krishnabrsivam@gmail.com",
"aswathi1232@gmail.com",
"sivaprasadshines43@gmail.com",
"krishnakinnuz@gmail.com",
"johnponnamkudam@gmail.com",
"kiranks985@gmail.com",
"aswinvs542@gmail.com",
"mradin1010@gmail.com",
"kashinathjasok@gmail.com",
"amalhishamkoraliyadan@gmail.com",
"alenmontu007@gmail.com",
"fasnausafmailbox@gmail.com",
"sidharth66pie@gmail.com",
"tthahir9@gmail.com",
"fadlasif123@gmail.com",
"kiranjayan18@gmail.com",
"jishnu3002@gmail.com",
"kkaromal2001@gmail.com",
"gopikasivadas167@gmail.com",
"sreeragkallur02@gmail.com",
"jishnushiju318@gmail.com",
"adithyanaadi7@gmail.com",
"muhammedthanveer1234@gmail.com",
"shaloofarif@gmail.com",
"aishwaryaranjith40@gmail.com",
"ziyadfiros@gmail.com",
"rahilroshan0001@gmail.com",
"ayshanahida003@gmail.com",
"chaithanyashajik@gmail.com",
"pranathiunnikrishnan@gmail.com",
"karthikkripa2002@gmail.com",
"aagnasnair@gmail.com",
"aiswaryaanoopkk3@gmail.com",
"sreelakshmib058@gmail.com",
"kadeejakv543@gmail.com",
"sabarinathkottammal123@gmail.com",
"ansamariya003@gmail.com",
"gemimava7@gmail.com",
"athuldevaraj1@gmail.com",
"adithyanandakumar10@gmail.com",
"shahinshakilinadan@gmail.com",
"midhunmano548@gmail.com",
"paiswariya2003@gmail.com",
"anjalijrajendran@gmail.com",
"brightymct@gmail.com",
"bakashbalu251203@gmail.com",
"anaghareghukumargkj@gmail.com",
"ashapchandren2019@gmail.com",
"abinajijohn14@gmail.com",
"rsabarisai2000@gmail.com",
"karthikskailas@gmail.com",
"gopikark2002@gmail.com",
"jocelyndaniel3@gmail.com"
])]


exports.learning = learning;
exports.project = project;
exports.venues = venues;
exports.mentors = mentors;
